#! /bin/sh
ldconfig


# Setting up interfaces
ip link set dev P10-eth0 up
ip -6 addr add fde4:3:f100:4::a/64 dev P10-eth0
ip link set dev P10-eth1 up
ip -6 addr add fde4:3:f200:5::a/64 dev P10-eth1
ip link set dev P10-eth2 up
ip -6 addr add fde4:3:f200:7::a/64 dev P10-eth2
ip link set dev lo up
ip -6 addr add fde4:3:f200::a/128 dev lo


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p10.api -i /tmp/p10_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p10_ospf.conf -z /tmp/p10.api -i /tmp/p10_ospf6d.pid -A 127.0.0.1 &
# launching bgpd
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p10_bgpd.conf -z /tmp/p10.api -i /tmp/p10_bgpd.pid -A 127.0.0.1
