#! /bin/sh
ldconfig


# Setting up interfaces
ip link set dev P12-eth0 up
ip -6 addr add fde4:3:9::c/64 dev P12-eth0
ip link set dev P12-eth1 up
ip -6 addr add fde4:3:a::c/64 dev P12-eth1
ip link set dev lo up
ip -6 addr add fde4:3::fc/128 dev lo


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p12.api -i /tmp/p12_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p12_ospf.conf -z /tmp/p12.api -i /tmp/p12_ospf6d.pid -A 127.0.0.1 &
# launching bgpd
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p12_bgpd.conf -z /tmp/p12.api -i /tmp/p12_bgpd.pid -A 127.0.0.1
