#! /bin/sh
ldconfig


# Setting up interfaces
ip link set dev P13-eth0 up
ip -6 addr add fde4:3:d::d/64 dev P13-eth0
ip link set dev P13-eth1 up
ip -6 addr add fde4:3:c::d/64 dev P13-eth1


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p13.api -i /tmp/p13_zebra.pid &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p13_ospf.conf -z /tmp/p13.api -i /tmp/p13_ospf6d.pid -A 127.0.0.1 &
# launching bgpd
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p13_bgpd.conf -z /tmp/p13.api -i /tmp/p13_bgpd.pid -A 127.0.0.1
