#! /bin/sh
ldconfig


# Setting up interfaces
ip link set dev P3-eth0 up
ip -6 addr add fde4:3:f100:3::3/64 dev P3-eth0
ip link set dev P3-eth1 up
ip -6 addr add fde4:3:f200:1::3/64 dev P3-eth1
ip link set dev P3-eth2 up
ip -6 addr add fde4:3:f200:2::3/64 dev P3-eth2
ip link set dev lo up
ip -6 addr add fde4:3:f200::3/128 dev lo


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p3.api -i /tmp/p3_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p3_ospf.conf -z /tmp/p3.api -i /tmp/p3_ospf6d.pid -A 127.0.0.1 &
# launching bgpd
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p3_bgpd.conf -z /tmp/p3.api -i /tmp/p3_bgpd.pid -A 127.0.0.1
