#! /bin/sh
ldconfig


# Setting up interfaces
ip link set dev P7-eth0 up
ip -6 addr add fde4:3:4::7/64 dev P7-eth0
ip link set dev P7-eth1 up
ip -6 addr add fde4:3:6::7/64 dev P7-eth1
ip link set dev P7-eth2 up
ip -6 addr add fde4:3:b::7/64 dev P7-eth2
ip link set dev P7-eth3 up
ip -6 addr add fde4:3:e::7/64 dev P7-eth3
ip link set dev lo up
ip -6 addr add fde4:3::f7/128 dev lo


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/p7.api -i /tmp/p7_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/p7_ospf.conf -z /tmp/p7.api -i /tmp/p7_ospf6d.pid -A 127.0.0.1 &
# launching bgpd
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/p7_bgpd.conf -z /tmp/p7.api -i /tmp/p7_bgpd.pid -A 127.0.0.1
