#! /bin/bash

# Startup script for router R02

ldconfig





ip -6 addr add fde4:4:f000:1::2/128 dev lo

   
ip link set dev R02-eth0 up
ip -6 addr add fde4:4:f000::7/127 dev R02-eth0
   
ip link set dev R02-eth1 up
ip -6 addr add fde4:4:f000::a/127 dev R02-eth1
   
ip link set dev R02-eth2 up
ip -6 addr add fde4:4:f000::c/127 dev R02-eth2
   
ip link set dev R02-eth3 up
ip -6 addr add fde4:4:f000::e/127 dev R02-eth3



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/R02_zebra.conf -z /tmp/R02.api -i /tmp/R02_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/R02_ospf.conf -z /tmp/R02.api -i /tmp/R02_ospf6d.pid -A 127.0.0.1 &

#lauching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/R02_bgpd.conf -z /tmp/R02.api -i /tmp/R02_bgpd.pid -A 127.0.0.1 &

# Launching nftables firewall
LD_LIBRARY_PATH=/usr/local/lib nft -f /etc/R02_nftables.conf
