#! /bin/bash

# Startup script for router R03

ldconfig





ip -6 addr add fde4:4:f000:1::3/128 dev lo

   
ip link set dev R03-eth0 up
ip -6 addr add fde4:4:f000::3/127 dev R03-eth0
   
ip link set dev R03-eth1 up
ip -6 addr add fde4:4:f000::10/127 dev R03-eth1
   
ip link set dev R03-eth2 up
ip -6 addr add fde4:4:f000::12/127 dev R03-eth2
   
ip link set dev R03-eth3 up
ip -6 addr add fde4:4:f000::14/127 dev R03-eth3
   
ip link set dev R03-eth4 up
ip -6 addr add fde4:4:f000::31/127 dev R03-eth4



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/R03_zebra.conf -z /tmp/R03.api -i /tmp/R03_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/R03_ospf.conf -z /tmp/R03.api -i /tmp/R03_ospf6d.pid -A 127.0.0.1 &

#lauching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/R03_bgpd.conf -z /tmp/R03.api -i /tmp/R03_bgpd.pid -A 127.0.0.1 &

# Launching nftables firewall
LD_LIBRARY_PATH=/usr/local/lib nft -f /etc/R03_nftables.conf
