#! /bin/bash

# Startup script for router R06

ldconfig





ip -6 addr add fde4:4:f000:1::6/128 dev lo

   
ip link set dev R06-eth0 up
ip -6 addr add fde4:4:f000::d/127 dev R06-eth0
   
ip link set dev R06-eth1 up
ip -6 addr add fde4:4:f000::19/127 dev R06-eth1
   
ip link set dev R06-eth2 up
ip -6 addr add fde4:4:f000::1d/127 dev R06-eth2
   
ip link set dev R06-eth3 up
ip -6 addr add fde4:4:f000::1e/127 dev R06-eth3



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/R06_zebra.conf -z /tmp/R06.api -i /tmp/R06_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/R06_ospf.conf -z /tmp/R06.api -i /tmp/R06_ospf6d.pid -A 127.0.0.1 &

#lauching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/R06_bgpd.conf -z /tmp/R06.api -i /tmp/R06_bgpd.pid -A 127.0.0.1 &

# Launching nftables firewall
LD_LIBRARY_PATH=/usr/local/lib nft -f /etc/R06_nftables.conf
