#! /bin/bash

# Startup script for router R07

ldconfig





ip -6 addr add fde4:4:f000:1::7/128 dev lo

   
ip link set dev R07-eth0 up
ip -6 addr add fde4:4:f000::9/127 dev R07-eth0
   
ip link set dev R07-eth1 up
ip -6 addr add fde4:4:f000::11/127 dev R07-eth1
   
ip link set dev R07-eth2 up
ip -6 addr add fde4:4:f000::1b/127 dev R07-eth2
   
ip link set dev R07-eth3 up
ip -6 addr add fde4:4:f000::20/127 dev R07-eth3



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/R07_zebra.conf -z /tmp/R07.api -i /tmp/R07_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/R07_ospf.conf -z /tmp/R07.api -i /tmp/R07_ospf6d.pid -A 127.0.0.1 &

#lauching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/R07_bgpd.conf -z /tmp/R07.api -i /tmp/R07_bgpd.pid -A 127.0.0.1 &

# Launching nftables firewall
LD_LIBRARY_PATH=/usr/local/lib nft -f /etc/R07_nftables.conf
