#! /bin/bash

# Startup script for router R08

ldconfig





ip -6 addr add fde4:4:f000:1::8/128 dev lo

   
ip link set dev R08-eth0 up
ip -6 addr add fde4:4:f000::f/127 dev R08-eth0
   
ip link set dev R08-eth1 up
ip -6 addr add fde4:4:f000::17/127 dev R08-eth1
   
ip link set dev R08-eth2 up
ip -6 addr add fde4:4:f000::1f/127 dev R08-eth2
   
ip link set dev R08-eth3 up
ip -6 addr add fde4:4:f000::21/127 dev R08-eth3



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/R08_zebra.conf -z /tmp/R08.api -i /tmp/R08_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/R08_ospf.conf -z /tmp/R08.api -i /tmp/R08_ospf6d.pid -A 127.0.0.1 &

#lauching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/R08_bgpd.conf -z /tmp/R08.api -i /tmp/R08_bgpd.pid -A 127.0.0.1 &

# Launching nftables firewall
LD_LIBRARY_PATH=/usr/local/lib nft -f /etc/R08_nftables.conf
