#! /bin/bash

# Startup script for router R11

ldconfig





ip -6 addr add fde4:4:f000:1::b/128 dev lo

   
ip link set dev R11-eth0 up
ip -6 addr add fde4:4:f000::25/127 dev R11-eth0
   
ip link set dev R11-eth1 up
ip -6 addr add fde4:4:f000::28/127 dev R11-eth1
   
ip link set dev R11-eth2 up
ip -6 addr add fde4:4:f000::33/127 dev R11-eth2



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/R11_zebra.conf -z /tmp/R11.api -i /tmp/R11_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/R11_ospf.conf -z /tmp/R11.api -i /tmp/R11_ospf6d.pid -A 127.0.0.1 &


#configuring the bgp interfaces
ip link set dev bgp_as65005 up
ip -6 addr add fde4:4:f001:5::beef/64 dev bgp_as65005 
#lauching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/R11_bgpd.conf -z /tmp/R11.api -i /tmp/R11_bgpd.pid -A 127.0.0.1 &

# Launching nftables firewall
LD_LIBRARY_PATH=/usr/local/lib nft -f /etc/R11_nftables.conf
