#! /bin/bash

# Startup script for router R12

ldconfig





ip -6 addr add fde4:4:f000:1::c/128 dev lo

   
ip link set dev R12-eth0 up
ip -6 addr add fde4:4:f000::29/127 dev R12-eth0
   
ip link set dev R12-eth1 up
ip -6 addr add fde4:4:f000::2b/127 dev R12-eth1
   
ip link set dev R12-eth2 up
ip -6 addr add fde4:4:f000::2e/127 dev R12-eth2



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/R12_zebra.conf -z /tmp/R12.api -i /tmp/R12_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/R12_ospf.conf -z /tmp/R12.api -i /tmp/R12_ospf6d.pid -A 127.0.0.1 &


#configuring the bgp interfaces
ip link set dev bgp_as65002 up
ip -6 addr add fde4:4:f001::4:dead/64 dev bgp_as65002 
#lauching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/R12_bgpd.conf -z /tmp/R12.api -i /tmp/R12_bgpd.pid -A 127.0.0.1 &

# Launching nftables firewall
LD_LIBRARY_PATH=/usr/local/lib nft -f /etc/R12_nftables.conf
