#! /bin/bash

# Startup script for router R14

ldconfig





ip -6 addr add fde4:4:f000:1::e/128 dev lo

   
ip link set dev R14-eth0 up
ip -6 addr add fde4:4:f000::32/127 dev R14-eth0
   
ip link set dev R14-eth1 up
ip -6 addr add fde4:4:f000::34/127 dev R14-eth1



# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/R14_zebra.conf -z /tmp/R14.api -i /tmp/R14_zebra.pid --v6-rr-semantics &

# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/R14_ospf.conf -z /tmp/R14.api -i /tmp/R14_ospf6d.pid -A 127.0.0.1 &


#configuring the bgp interfaces
ip link set dev bgp_as65008 up
ip -6 addr add fde4:8:b004::beef/64 dev bgp_as65008 
#lauching FRRouting BGP daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/R14_bgpd.conf -z /tmp/R14.api -i /tmp/R14_bgpd.pid -A 127.0.0.1 &

# Launching nftables firewall
LD_LIBRARY_PATH=/usr/local/lib nft -f /etc/R14_nftables.conf
